version: "2017-09-20"
notifications:
  hipchat:
    rooms:
     - cdp-notifications-test
pipeline:
  - id: build
    type: script
    overlay: ci/python
    commands:
    - desc: "Install dependencies"
      cmd: pip install -r requirements.txt
    - desc: "Run Tests"
      cmd: python3 setup.py test
    - desc: "Check code style"
      cmd: python3 setup.py flake8
    - desc: "Build docker image that will upload package"
      cmd: |
        VERSION=$(./next-version)

        if [[ -z "${CDP_PULL_REQUEST_NUMBER}" ]]; then
          DOCKER_IMAGE="pierone.stups.zalan.do/automata/senza:${VERSION}"
        else
          DOCKER_IMAGE="pierone.stups.zalan.do/automata/senza:${VERSION}-snapshot"
        fi

        docker build --build-arg VERSION="$VERSION" -t "$DOCKER_IMAGE" .
